Chore/#1 Update issue templates
studio-mesh/.github pull request #3
Opened 2023-07-05 10:49 UTC by uchiyama-mesh

## 概要

Issue: close #1 

やったこと
- 開発手順で定義した8つのissueテンプレートを作成

![スクリーンショット 2023-07-05 19 47 41](https://github.com/studio-mesh/.github/assets/100283315/08de5e7f-fc8b-4be6-ad7b-c6527af13d07)

後回しにしたこと
- なし

## テスト

リリース後に実施するテスト
- 他のリポジトリでissueテンプレートが選択できること

## Ready for Review チェックリスト

- [x] PR名が作業の目的を表現している
- [x] PR名にFeat/#xxのPrefixがついている
- [x] ブランチ名は[ChatGPTが作成した](https://www.notion.so/smesh/branch-02473bd31dd74d5da9b29a33ea61d763)
- [ ] README/docの追加・更新を完了済み
- [ ] TODOおよび未対応箇所のIssuesを発行済み

## テスト方法・確認環境

```
```

## Memo

2023-07-05 11:47 UTC, kiyota-mesh commented
@uchiyama-mesh 
PRのテンプレは更新しないんでしたっけ？

2023-07-05 12:27 UTC, uchiyama-mesh commented
@kiyota-mesh 
PRテンプレートも更新しました。

2023-07-06 04:25 UTC, kiyota-mesh requested changes
@uchiyama-mesh 
コメントしました💡

2023-07-06 04:25 UTC, kiyota-mesh commented on .github/ISSUE_TEMPLATE/bug.md
> +## 修正しないときの影響
修正の意図が分からないので教えてください。

2023-07-06 04:25 UTC, kiyota-mesh commented on .github/ISSUE_TEMPLATE/chore.md
仕様は不要ですか？

2023-07-06 04:25 UTC, kiyota-mesh commented on .github/ISSUE_TEMPLATE/docs.md
> +## 仕様と制約
例えばどのようなことを記載しますか？

2023-07-06 04:25 UTC, kiyota-mesh commented on .github/ISSUE_TEMPLATE/docs.md
> +## ドキュメントの対象者
```suggestion
## 作成または変更するドキュメント
```

2023-07-06 04:25 UTC, kiyota-mesh commented on .github/ISSUE_TEMPLATE/feature.md
> +## 仕様と制約
制約は仕様の一部では？何かを参考にしました？

2023-07-06 04:25 UTC, kiyota-mesh commented on .github/ISSUE_TEMPLATE/fix.md
fixとbugはどう使い分けますか？

2023-07-06 04:25 UTC, kiyota-mesh commented on .github/ISSUE_TEMPLATE/perf.md
パフォーマンスをどう改善するかを記載する部分がありません。

2023-07-06 04:25 UTC, kiyota-mesh commented on .github/ISSUE_TEMPLATE/refactor.md
> +## リファクタリングの影響がある画面・機能
画面、機能に影響を与えないものをリファクタリングといいます。

2023-07-06 04:25 UTC, kiyota-mesh commented on docs/pull_request_template.md
> +後回しにしたことは、issue を発行し、リンクを記載する
- sampleのあとに#をつけた方が親切です
- 記載方法はチェックリストにまとめたほうが分かりやすいです。

2023-07-06 04:25 UTC, kiyota-mesh commented on docs/pull_request_template.md
> +- [ ] ユニットテスト
リリース前のテストを記載するメリットはありますか？

2023-07-06 04:25 UTC, kiyota-mesh commented on docs/pull_request_template.md
> +テストケースを notion に記載して、リンクを追加してもよい
- 実施するテストの種類を書くのか、ケースを書くのか混乱します。
- 記載方法はチェックリストにまとめたほうが分かりやすいです。

2023-07-06 08:17 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/bug.md
> +## 修正しないときの影響
@kiyota-mesh 
他の項目が体言止めしてたので、合わせたかったという理由です。
ですが`困ること`ということが明示されなくなったので、少し意味が変わりました。
戻した方が良いでしょうか？

2023-07-06 08:24 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/docs.md
> +## 仕様と制約
@kiyota-mesh 
どんなフォーマット（notion、excel等）で作成するか、ドキュメントに記載する項目とかです。

2023-07-06 08:27 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/feature.md
> +## 仕様と制約
@kiyota-mesh 
いえ、参考してなくて、個人的に分けてあった方が考えやすいかなと思い、制約を追記しました。
意図としては、`~をする`は思いつきやすいけど、`~はしない`みたいなのが、ちゃんと記載できるといいなという意図です。

2023-07-06 08:45 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/chore.md
@kiyota-mesh 
仕様を追加しました。
https://github.com/studio-mesh/.github/pull/3/commits/dc697fe4885f7093b5a0ab4f5c7955996fdabd56

2023-07-06 08:48 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/fix.md
@kiyota-mesh 
fixは既存機能を良くするための改修、bugは不具合（既存機能の悪い箇所）の改修で使い分けます。

2023-07-06 08:48 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/perf.md
@kiyota-mesh 
パフォーマンスの改善方法の項目を追加しました。
https://github.com/studio-mesh/.github/pull/3/commits/dc697fe4885f7093b5a0ab4f5c7955996fdabd56

2023-07-06 08:49 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/refactor.md
> +## リファクタリングの影響がある画面・機能
@kiyota-mesh 
影響ではなく、リファクタリング対象の機能・画面という項目に変更しました。
https://github.com/studio-mesh/.github/pull/3/commits/dc697fe4885f7093b5a0ab4f5c7955996fdabd56

2023-07-06 08:50 UTC, uchiyama-mesh commented on docs/pull_request_template.md
> +後回しにしたことは、issue を発行し、リンクを記載する
@kiyota-mesh 
sampleのあとに#をつけました。
リンクを記載したかどうかは、Ready for Reviewのチェックリストに追加しました。
https://github.com/studio-mesh/.github/pull/3/commits/dc697fe4885f7093b5a0ab4f5c7955996fdabd56

2023-07-06 08:50 UTC, uchiyama-mesh commented on docs/pull_request_template.md
> +- [ ] ユニットテスト
@kiyota-mesh 
リリース前のテストの項目を削除しました。
https://github.com/studio-mesh/.github/pull/3/commits/dc697fe4885f7093b5a0ab4f5c7955996fdabd56

2023-07-06 08:51 UTC, uchiyama-mesh commented on docs/pull_request_template.md
> +テストケースを notion に記載して、リンクを追加してもよい
@kiyota-mesh 
テストの種類ではなく、実施する内容でテストのチェックリストを作成しました。
sampleの行を追加して、#以降で補足を記載しました。
https://github.com/studio-mesh/.github/pull/3/commits/dc697fe4885f7093b5a0ab4f5c7955996fdabd56

2023-07-06 12:14 UTC, kiyota-mesh commented on .github/ISSUE_TEMPLATE/bug.md
> +## 修正しないときの影響
体言止めにしたいだけなら、`困ること`でいいんじゃないでしょうか。

2023-07-06 12:15 UTC, kiyota-mesh commented on .github/ISSUE_TEMPLATE/chore.md
リンク間違えてますか？

2023-07-06 12:18 UTC, kiyota-mesh commented on .github/ISSUE_TEMPLATE/feature.md
> +## 仕様と制約
仕様にしてください。
要件とシステム制約、とかなら分かりますが、細かくなりすぎます。

2023-07-06 12:18 UTC, kiyota-mesh commented on .github/ISSUE_TEMPLATE/perf.md
リンク間違えてますか？

2023-07-06 12:18 UTC, kiyota-mesh commented on .github/ISSUE_TEMPLATE/refactor.md
> +## リファクタリングの影響がある画面・機能
リンク間違えてますか？

2023-07-06 12:19 UTC, kiyota-mesh commented on docs/pull_request_template.md
> +後回しにしたことは、issue を発行し、リンクを記載する
リンク間違えてますか？

2023-07-06 12:19 UTC, kiyota-mesh commented on docs/pull_request_template.md
> +- [ ] ユニットテスト
リンク間違えてますか？

2023-07-06 12:20 UTC, kiyota-mesh commented on docs/pull_request_template.md
> +テストケースを notion に記載して、リンクを追加してもよい
リンク間違えてますか？

2023-07-06 16:15 UTC, uchiyama-mesh commented on docs/pull_request_template.md
> +- [ ] ユニットテスト
@kiyota-mesh 
リリース前のテストを追加した理由は、開発手順として、PR作成前にローカルでユニットテストやe2eテストをすることが記載されているので、それをやったかどうかのチェックのためです。

2023-07-06 16:16 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/chore.md
@kiyota-mesh 
リンク貼り間違えてました。
https://github.com/studio-mesh/.github/pull/3/commits/ebbc32eab5b6f0420451c6de698d917d90b563a5

2023-07-06 16:16 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/perf.md
@kiyota-mesh 
リンク貼り間違えてました。
https://github.com/studio-mesh/.github/pull/3/commits/ebbc32eab5b6f0420451c6de698d917d90b563a5

2023-07-06 16:16 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/refactor.md
> +## リファクタリングの影響がある画面・機能
@kiyota-mesh 
リンク貼り間違えてました。
https://github.com/studio-mesh/.github/pull/3/commits/ebbc32eab5b6f0420451c6de698d917d90b563a5

2023-07-06 16:17 UTC, uchiyama-mesh commented on docs/pull_request_template.md
> +後回しにしたことは、issue を発行し、リンクを記載する
@kiyota-mesh 
リンク貼り間違えてました。
https://github.com/studio-mesh/.github/pull/3/commits/ebbc32eab5b6f0420451c6de698d917d90b563a5

2023-07-06 16:17 UTC, uchiyama-mesh commented on docs/pull_request_template.md
> +テストケースを notion に記載して、リンクを追加してもよい
@kiyota-mesh 
リンク貼り間違えてました。
https://github.com/studio-mesh/.github/pull/3/commits/ebbc32eab5b6f0420451c6de698d917d90b563a5

2023-07-06 16:22 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/bug.md
> +## 修正しないときの影響
@kiyota-mesh 
`困ること`で修正しました。
https://github.com/studio-mesh/.github/pull/3/commits/ff52427a99ba8c8388de8414cb5ad8c89ef0473e#diff-b577c75bfe1a70d8f33d404b7aa81aff373147db26fe6d5a54283c3dea107f83R19

2023-07-06 16:23 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/feature.md
> +## 仕様と制約
@kiyota-mesh 
仕様に修正しました。
https://github.com/studio-mesh/.github/pull/3/commits/ff52427a99ba8c8388de8414cb5ad8c89ef0473e

2023-07-06 16:23 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/docs.md
> +## 仕様と制約
@kiyota-mesh 
こちらはいかがでしょう？

2023-07-06 16:24 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/fix.md
@kiyota-mesh 
こちらはいかがでしょう？

2023-07-06 18:33 UTC, kiyota-mesh commented on docs/pull_request_template.md
> +後回しにしたことは、issue を発行し、リンクを記載する
@uchiyama-mesh 
説明とチェックリストの内容が重複してます。

2023-07-06 18:38 UTC, kiyota-mesh commented on docs/pull_request_template.md
> +- [ ] ユニットテスト
@uchiyama-mesh 
正しいリンクを記載してください。
ユニットテストはCIで実行されるので、記載は不要ではないですか？あとe2eってリリース前にやるんでしたっけ？

2023-07-06 18:41 UTC, kiyota-mesh commented on docs/pull_request_template.md
> +- [ ] 後回しにしたことを Issue として発行して、そのリンクを PR に記載済
```suggestion
- [ ] 後回しにしたことを Issue として発行して、リンクを記載済
```

2023-07-06 23:36 UTC, uchiyama-mesh commented on docs/pull_request_template.md
> +- [ ] ユニットテスト
@kiyota-mesh 
リリース前のユニットテストの項目を削除したコミットのリンクをこちらになります。
https://github.com/studio-mesh/.github/commit/ebbc32eab5b6f0420451c6de698d917d90b563a5#diff-d915bbd02901ffd904dbc4f89f0849e9485d246c2b5b0fbdc021f564550837bbL19

PR作成前に、ローカル環境を使ってユニットテストとe2eテストをやったかどうか。を確認する項目という意図で記載したのですが、`リリース前`というのが不適切でした。
そして、PR作成後もコードが変更されていくので、チェックの意味がないので、この項目は削除して、開発手順の記載だけにとどめようと思います。

2023-07-06 23:39 UTC, uchiyama-mesh commented on docs/pull_request_template.md
> +- [ ] 後回しにしたことを Issue として発行して、そのリンクを PR に記載済
@kiyota-mesh 
修正しました。
https://github.com/studio-mesh/.github/commit/e75fdb6143b84e9d57436cda2ef3237a37d291de#diff-d915bbd02901ffd904dbc4f89f0849e9485d246c2b5b0fbdc021f564550837bbR28

2023-07-06 23:40 UTC, uchiyama-mesh commented on docs/pull_request_template.md
> +後回しにしたことは、issue を発行し、リンクを記載する
@kiyota-mesh 
後に回したことの項目の方の説明を削除しました。
https://github.com/studio-mesh/.github/commit/e75fdb6143b84e9d57436cda2ef3237a37d291de#diff-d915bbd02901ffd904dbc4f89f0849e9485d246c2b5b0fbdc021f564550837bbR11

2023-07-07 01:41 UTC, kiyota-mesh commented on docs/pull_request_template.md
> +後回しにしたことは、issue を発行し、リンクを記載する
@uchiyama-mesh 
最初のコメントですが、#はあったほうが親切ではないですか？

2023-07-07 01:45 UTC, kiyota-mesh commented
@uchiyama-mesh 
本PRの `close #1 #2`だとissueとひも付きません。`close #1, close #2`とする必要があります。
あとAssigneeも設定してください。

2023-07-07 02:57 UTC, uchiyama-mesh commented on docs/pull_request_template.md
> +後回しにしたことは、issue を発行し、リンクを記載する
@kiyota-mesh 
後回しにしたことの項目に#を付け直しました。

```md
### 後回しにしたこと

- sample # 後回しにしたことは、issue を発行する
```

https://github.com/studio-mesh/.github/commit/1ac03eceb5bb5903d508d80398c089cea959df9f
commitは、force pushしたため、上記のコードは変更なしになってます。

2023-07-07 02:57 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/fix.md
@kiyota-mesh 
こちらはいかがでしょう？

2023-07-07 03:14 UTC, uchiyama-mesh commented on docs/pull_request_template.md
> +後回しにしたことは、issue を発行し、リンクを記載する
@kiyota-mesh 
修正しました。
https://github.com/studio-mesh/.github/commit/ce6a5cf3be1d8d46ef9a10c21a96e3f67dd779b7

2023-07-07 03:19 UTC, kiyota-mesh approved these changes
@uchiyama-mesh 
Approved🦭

2023-07-07 03:37 UTC, uchiyama-mesh commented on .github/ISSUE_TEMPLATE/fix.md
@kiyota-mesh 
修正しました。
https://github.com/studio-mesh/.github/pull/3/commits/7bf43e0dce1a0afab4936e56b35678cbc1034437

2023-07-07 03:50 UTC, uchiyama-mesh commented
@kiyota-mesh 
PRのテストの項目を修正しました。
https://github.com/studio-mesh/.github/pull/3/commits/a1eed4d140c03be55899bd46f846daecc4112e19
また、開発手順の該当箇所も修正しました。
https://www.notion.so/smesh/93974d4113254d34a828bff8890dcf74?pvs=4#3a8ffa2f99844c37b820955afbc52cb2

2023-07-07 03:59 UTC, kiyota-mesh approved these changes
@uchiyama-mesh 
Approved🦤

2023-07-07 04:05 UTC, merged