Feat/#4 update templates
studio-mesh/.github pull request #5
Opened 2023-08-28 07:05 UTC by uchiyama-mesh

## 概要

Issue: close #4 

### やったこと

- [x] `Ready for Review`チェックリストの更新
  - ブランチ名のチェックを削除
  - CIの実行結果確認のチェックを追加

### 後回しにしたこと

- なし

## リリース後に実施するテスト

- なし

## Ready for Review チェックリスト

- [x] PR 名が作業の目的を表現している
- [x] PR 名に Feat/#xx の Prefix がついている
- [ ] ブランチ名は[ChatGPT が作成した](https://www.notion.so/smesh/branch-02473bd31dd74d5da9b29a33ea61d763)
- [x] README/doc の追加・更新を完了済み
- [x] 全てのやったことにチェックがついている
- [x] コード内の TODO および後回しにしたことを issue として発行して、リンクを記載済み

## Memo

- レビュワーへの参考情報（やったことの実装詳細、画面スクショなど）

2023-08-28 09:06 UTC, kiyota-mesh requested changes
@uchiyama-mesh 
Commented

2023-08-28 09:06 UTC, kiyota-mesh commented on docs/pull_request_template.md
> +- sample
sampleには何を記載するんですか？

2023-08-28 09:06 UTC, kiyota-mesh commented on docs/pull_request_template.md
> +- [ ] CI の実行結果を確認済み
```suggestion
- [ ] CI がPassしている
```

2023-08-28 09:06 UTC, kiyota-mesh commented on docs/pull_request_template.md
>  - [ ] 全てのやったことにチェックがついている
```suggestion
```

2023-08-28 09:06 UTC, kiyota-mesh commented on docs/pull_request_template.md
>  - [ ] README/doc の追加・更新を完了済み
```suggestion
- [ ] README/doc が適切な状態にある
```

2023-08-28 09:06 UTC, kiyota-mesh commented on .vscode/settings.json
これは何の目的ですか？

2023-08-28 09:30 UTC, uchiyama-mesh commented on docs/pull_request_template.md
> +- sample
@uchiyama-mesh 
後回しにしたことを日本語で記載する想定です。
#{issue番号}でissue名が出ますが、日本語で記載した方がぱっと見で分かりやすいと思いました。

2023-08-28 09:31 UTC, uchiyama-mesh commented on .vscode/settings.json
このリポジトリのブランチ作成時に、githubの拡張機能でissue名からブランチ名を作成するためです。

2023-08-28 09:41 UTC, uchiyama-mesh commented on docs/pull_request_template.md
>  - [ ] README/doc の追加・更新を完了済み
@kiyota-mesh 
修正しました。
https://github.com/studio-mesh/.github/pull/5/commits/ca90180c0178f777907d19aa3cb328d5ad849c7e

2023-08-28 09:41 UTC, uchiyama-mesh commented on docs/pull_request_template.md
>  - [ ] 全てのやったことにチェックがついている
@kiyota-mesh 
修正しました。
https://github.com/studio-mesh/.github/pull/5/commits/ca90180c0178f777907d19aa3cb328d5ad849c7e

2023-08-28 09:41 UTC, uchiyama-mesh commented on docs/pull_request_template.md
> +- [ ] CI の実行結果を確認済み
@kiyota-mesh 
修正しました。
https://github.com/studio-mesh/.github/pull/5/commits/ca90180c0178f777907d19aa3cb328d5ad849c7e

2023-08-28 09:48 UTC, kiyota-mesh reviewed
Commented

2023-08-28 09:48 UTC, kiyota-mesh commented on docs/pull_request_template.md
> +- sample
元からそうなってたと思いますが、今回改行した理由はなんですか？

2023-08-28 09:48 UTC, kiyota-mesh commented on .vscode/settings.json
@uchiyama-mesh 
松井さんがterminalで実行した際の問題を指摘してましたが、この内容で行きますか？

2023-08-28 09:55 UTC, uchiyama-mesh commented on docs/pull_request_template.md
> +- sample
@kiyota-mesh 
後回しにしたこととissue名が、同行だと見づらいと思ったためです。

2023-08-28 09:57 UTC, uchiyama-mesh commented on .vscode/settings.json
@kiyota-mesh 
ブランチ名の頭の`#`を削除しているので、松井さんが挙げてくれた問題は解消されます。

2023-08-28 10:13 UTC, kiyota-mesh commented on .vscode/settings.json
@uchiyama-mesh 
えっ現状の方針を独断で変えたってことですか？そういう時は相談して欲しいです。
他のリポジトリの設定の変更も必要になりますけど、周知もするってことです？もうしてます？

2023-08-28 10:21 UTC, uchiyama-mesh commented on .vscode/settings.json
@kiyota-mesh 
> えっ現状の方針を独断で変えたってことですか？そういう時は相談して欲しいです。

すみません。開発方針に大きい影響が出る変更になりますね。
別途、相談させてください。（このファイルは削除します）

> 他のリポジトリの設定の変更も必要になりますけど、周知もするってことです？もうしてます？

まだ周知もしてなく、他のリポジトリの設定変更もしていないです。

2023-08-29 07:59 UTC, kiyota-mesh commented on .vscode/settings.json
@uchiyama-mesh 
これ対応待ちです

2023-08-29 08:00 UTC, uchiyama-mesh commented on .vscode/settings.json
@kiyota-mesh 
削除しました。
https://github.com/studio-mesh/.github/pull/5/commits/1642c9e7ab534f1f3963d16cc7d205a4c2294420

2023-08-29 08:03 UTC, kiyota-mesh approved these changes
@uchiyama-mesh 
Approved🙆‍♂️

2023-08-29 08:18 UTC, merged